### PR TITLE
[#115902693] upgrade aws sdk

### PR DESCRIPTION
**Pull request by genericname92**

### CODE REVIEW

**Comment by genericname92** [comment]
uh okay so all I did was change the pom.xml aws-java-sdk version and then run mvn clean install

**Comment by kirkchris** [comment]
should we gitignore the .idea folder and the .iml file?

**Comment by genericname92** [comment]
@kirkchris DO you want to approve this PR before I deploy this to prod?

**Comment by kirkchris** [comment]
YES I WOULD LIKE TO APPROVE

**Comment by kirkchris** [comment]
IT LOOKS GOOD

**Pull request merged**
